### ISSUE TITLE
is there a simple way to receive the SMS via http server? e.g. PHP on apache.

### ISSUE THREAD

**Issue by shula** [deku-messaging/deku-messaging.github.io#15]
I'd like to to run a gateway on my tiny server, to store low volume messages (2-3 sms a day)

Where are the specs? 
What my server should be looking for in the request from the deku phone app -> to my php server?

I've tried to capture all the request variables, 
The server received an incoming HTTP request, 
but I couldn't find there the data itself, only the sender info of the request.

Thanks!

**Comment by sherlockwisdom** [comment]
Unfortunately you opened the issue on the wrong repo

Here's a link to the repo and how it forwards to the cloud 

https://github.com/deku-messaging/Deku-SMS-Android?tab=readme-ov-file#-forward-incoming-messages-to-cloud
